name: sylseq
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab==3.5.3
  - matplotlib==3.5.1
  - numpy==1.23.5
  - pandas==1.3.5
  - pytables==3.8.0
  - scipy==1.8.0
  - seaborn==0.12.2
  - statannot==0.2.3
  - statsmodels==0.13.1
  - pip
  - pip:
    - matplotlib_venn==0.11.7
    - mne==0.20.7
    - scikit_learn==1.2.1
    - -e .